#!/bin/bash

set -eu
cd "$(dirname $0)"

dump() {
    cat $1
    echo ""
}

# Download ca-bundle from curl
curl -fsSL -o cache/curl.pem https://curl.haxx.se/ca/cacert.pem

find . -name "*.pem" -o -name "*.cer" | while read -r cert
do
    dump $cert
done
